train_dir: /mnt/lustre/zongdaoming/GNN-XMC/model_test/data/in_domain_train.tsv
epochs: 4
weight_decay_rate: 0.001
lr: 0.00002
saver_train: train_acc_set_2e_5_train.pkl
saver_test: test_acc_set_2e_5_test.pkl