train_dir: /mnt/lustre/zongdaoming/GNN-XMC/model_test/data/in_domain_train.tsv
epochs: 5
weight_decay_rate: 0.001
lr: 0.000002
saver_train: train_acc_set_2e_6_decay_001_train.pkl
saver_test: test_acc_set_2e_6_decay_001_test.pkl